[2023-10-05T14:35:53.546+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_to_bigquery_dag.load_to_bigquery manual__2023-10-05T14:35:46.590094+00:00 [queued]>
[2023-10-05T14:35:53.580+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_to_bigquery_dag.load_to_bigquery manual__2023-10-05T14:35:46.590094+00:00 [queued]>
[2023-10-05T14:35:53.582+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-05T14:35:53.633+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_to_bigquery> on 2023-10-05 14:35:46.590094+00:00
[2023-10-05T14:35:53.650+0000] {standard_task_runner.py:57} INFO - Started process 5595 to run task
[2023-10-05T14:35:53.790+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_to_bigquery_dag', 'load_to_bigquery', 'manual__2023-10-05T14:35:46.590094+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/load_to_bigquery_dag.py', '--cfg-path', '/tmp/tmp_l85o_l6']
[2023-10-05T14:35:53.832+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask load_to_bigquery
[2023-10-05T14:35:54.063+0000] {task_command.py:415} INFO - Running <TaskInstance: load_to_bigquery_dag.load_to_bigquery manual__2023-10-05T14:35:46.590094+00:00 [running]> on host bd744fef73d7
[2023-10-05T14:35:54.507+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='load_to_bigquery_dag' AIRFLOW_CTX_TASK_ID='load_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2023-10-05T14:35:46.590094+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-05T14:35:46.590094+00:00'
[2023-10-05T14:35:58.849+0000] {logging_mixin.py:151} INFO - Loaded 15 rows into /projects/arched-media-273319/datasets/mobileviking/tables/products_table
[2023-10-05T14:35:59.051+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bigquery.py", line 21, in load_json_to_bigquery
    with open(ndjson_file_path, "rb") as source_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/raw_data/ndjson/packs.ndjson'
[2023-10-05T14:35:59.087+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=load_to_bigquery_dag, task_id=load_to_bigquery, execution_date=20231005T143546, start_date=20231005T143553, end_date=20231005T143559
[2023-10-05T14:35:59.109+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 50 for task load_to_bigquery ([Errno 2] No such file or directory: 'data/raw_data/ndjson/packs.ndjson'; 5595)
[2023-10-05T14:35:59.176+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-05T14:35:59.199+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
