[2023-10-06T07:31:46.729+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_to_bigquery_dag.wait_for_file manual__2023-10-06T07:31:43.864339+00:00 [queued]>
[2023-10-06T07:31:46.739+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_to_bigquery_dag.wait_for_file manual__2023-10-06T07:31:43.864339+00:00 [queued]>
[2023-10-06T07:31:46.740+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-06T07:31:46.756+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonSensor): wait_for_file> on 2023-10-06 07:31:43.864339+00:00
[2023-10-06T07:31:46.776+0000] {standard_task_runner.py:57} INFO - Started process 12745 to run task
[2023-10-06T07:31:46.782+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_to_bigquery_dag', 'wait_for_file', 'manual__2023-10-06T07:31:43.864339+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/load_to_bigquery_dag.py', '--cfg-path', '/tmp/tmp_mtdyh24']
[2023-10-06T07:31:46.785+0000] {standard_task_runner.py:85} INFO - Job 54: Subtask wait_for_file
[2023-10-06T07:31:46.907+0000] {task_command.py:415} INFO - Running <TaskInstance: load_to_bigquery_dag.wait_for_file manual__2023-10-06T07:31:43.864339+00:00 [running]> on host bd744fef73d7
[2023-10-06T07:31:47.026+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='load_to_bigquery_dag' AIRFLOW_CTX_TASK_ID='wait_for_file' AIRFLOW_CTX_EXECUTION_DATE='2023-10-06T07:31:43.864339+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-06T07:31:43.864339+00:00'
[2023-10-06T07:31:47.029+0000] {python.py:72} INFO - Poking callable: <function check_files_exist at 0xffff909b1310>
[2023-10-06T07:31:47.031+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/python.py", line 73, in poke
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: check_files_exist() missing 1 required positional argument: 'file_names'
[2023-10-06T07:31:47.045+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=load_to_bigquery_dag, task_id=wait_for_file, execution_date=20231006T073143, start_date=20231006T073146, end_date=20231006T073147
[2023-10-06T07:31:47.056+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 54 for task wait_for_file (check_files_exist() missing 1 required positional argument: 'file_names'; 12745)
[2023-10-06T07:31:47.084+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
