[2023-10-05T14:35:53.503+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_to_bigquery_dag.wait_for_file manual__2023-10-05T14:35:46.590094+00:00 [queued]>
[2023-10-05T14:35:53.535+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_to_bigquery_dag.wait_for_file manual__2023-10-05T14:35:46.590094+00:00 [queued]>
[2023-10-05T14:35:53.551+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-05T14:35:53.595+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonSensor): wait_for_file> on 2023-10-05 14:35:46.590094+00:00
[2023-10-05T14:35:53.613+0000] {standard_task_runner.py:57} INFO - Started process 5594 to run task
[2023-10-05T14:35:53.631+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_to_bigquery_dag', 'wait_for_file', 'manual__2023-10-05T14:35:46.590094+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/load_to_bigquery_dag.py', '--cfg-path', '/tmp/tmp6jd8nryc']
[2023-10-05T14:35:53.755+0000] {standard_task_runner.py:85} INFO - Job 49: Subtask wait_for_file
[2023-10-05T14:35:54.073+0000] {task_command.py:415} INFO - Running <TaskInstance: load_to_bigquery_dag.wait_for_file manual__2023-10-05T14:35:46.590094+00:00 [running]> on host bd744fef73d7
[2023-10-05T14:35:54.542+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='load_to_bigquery_dag' AIRFLOW_CTX_TASK_ID='wait_for_file' AIRFLOW_CTX_EXECUTION_DATE='2023-10-05T14:35:46.590094+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-05T14:35:46.590094+00:00'
[2023-10-05T14:35:54.579+0000] {python.py:72} INFO - Poking callable: <function check_files_exist at 0xffff9099a310>
[2023-10-05T14:35:54.584+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/python.py", line 73, in poke
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: check_files_exist() missing 1 required positional argument: 'file_names'
[2023-10-05T14:35:54.627+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=load_to_bigquery_dag, task_id=wait_for_file, execution_date=20231005T143546, start_date=20231005T143553, end_date=20231005T143554
[2023-10-05T14:35:54.713+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 49 for task wait_for_file (check_files_exist() missing 1 required positional argument: 'file_names'; 5594)
[2023-10-05T14:35:54.815+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-05T14:35:54.860+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
